branches:
  only:
    - AppVeyor
version: 1.0.{build}
nuget:
  project_feed: true
before_build:
  - nuget restore
build:
  project: VerbalExpressions.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal